AWSTemplateFormatVersion: 2010-09-09

Parameters :
  UserName: 
    Type: String
  PolicyName:
    Type: String


Resources:
  TestUser:
    Type: AWS::IAM::User
    Properties:
        UserName: !Ref UserName

  ReadOnlyS3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 
        !Join
          - '-'
          -
            - 'ROS3ManagedPolicy'
            - !Ref AWS::Region
      Users:
        - !Ref 'UserName'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Sid: AllowAllUsersToListAccounts
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: "*"

Outputs:
  PolicyARN:
    Value: !Ref ReadOnlyS3Policy
    Export:
      Name: PolicyName