AWSTemplateFormatVersion: "2010-09-09"
Description:
  Make an S3 Bucket


Parameters : 
  BucketName:
    Type: "String"
    Description: "Name of Bucket for THUNDERSTACK"
    Default: "ph-example-bucket-name-1"
  OwnerName:
    Description: "Owner of the bucket"
    Type: String
    Default: "SRE"
  

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName 
      Tags:
        -
          Key: "Owner"
          Value: !Ref OwnerName

Outputs:
  Bucket:
    Description:  S3 Bucket creation complete
    Value: !Join #Fn::Join
       - ''
       -  
         - !Ref BucketName
         - !Ref AWS::AccountId
