AWSTemplateFormatVersion: "2010-09-09"
Description:
  Make an S3 Bucket


Parameters : 
  BucketName:
    Type: "String"
    Description: "Name of Bucket for THUNDERSTACK"
    Default: "ph-example-bucket-name-1"
  OwnerName:
    Description: "Owner of the bucket"
    Type: String
    Default: "SRE"
  
Conditions:
  PreferredRegion: !Equals 
    - !Ref AWS::Region
    - us-east-2
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !If #Fn::If
          - PreferredRegion
          - !Join #Fn::Join
            - '-'
            - - !Ref AWS::AccountId
              - !Ref BucketName
          - !Join #Fn::Join
            - '-'
            - - !Ref AWS::Region
              - !Ref BucketName
  

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName 
      Tags:
        -
          Key: "Owner"
          Value: !Ref OwnerName

Outputs:
  Bucket:
    Description:  S3 Bucket creation complete
    Value: !Join #Fn::Join
       - ''
       -  
         - !Ref BucketName
         - !Ref AWS::AccountId
