AWSTemplateFormatVersion: "2010-09-09"
Description:
  Make an S3 Bucket

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName 
        

"Parameters" : 
  BucketName:
    Type: "String"
    Description: "Name of Bucket for THUNDERSTACK"
    Default: "ph-example-bucket-name-1"